"use client";
import Link from "next/link";
import { useEffect, useMemo } from "react";
import { useFileDistribution } from "./file-distribution-provider";
import { DistributionConnectionBadge } from "./distribution-connection-badge";
import { DistributionStatusBadge } from "./distribution-status-badge";
import { DistributionProgress } from "./distribution-progress";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { formatRelativeTime, type DistributionListSummary, type DistributionPagination, type FileDistributionJob } from "@/lib/file-distribution";

type Snapshot = { jobs: FileDistributionJob[]; summary: DistributionListSummary; pagination: DistributionPagination };
export function DistributionList({ initialSnapshot, query, filter }: { initialSnapshot: Snapshot; query: string; filter: string }) {
  const { jobs: liveJobs, connection, hydrateJobs } = useFileDistribution();
  useEffect(() => hydrateJobs(initialSnapshot.jobs), [hydrateJobs, initialSnapshot.jobs]);
  const jobs = useMemo(() => initialSnapshot.jobs.map((job) => liveJobs[job.id] ?? job), [initialSnapshot.jobs, liveJobs]);
  const cards = [["งานทั้งหมด", initialSnapshot.summary.totalJobs, "bg-blue-500"], ["กำลังดำเนินการ", initialSnapshot.summary.inProgress, "bg-amber-500"], ["สำเร็จ", initialSnapshot.summary.completed, "bg-emerald-500"], ["ไม่สำเร็จ", initialSnapshot.summary.failed, "bg-red-500"]] as const;
  return <div className="mx-auto w-full max-w-7xl space-y-6">
    <header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-blue-700 via-blue-600 to-cyan-500 p-6 text-white shadow-lg shadow-blue-600/10 sm:p-8"><div className="absolute -right-12 -top-20 size-56 rounded-full bg-white/10" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold tracking-[0.18em] text-blue-100">ศูนย์จัดการไฟล์</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">งานกระจายไฟล์</h1><p className="mt-2 text-sm text-blue-50 sm:text-base">ติดตามความคืบหน้าและผลการส่งไฟล์ไปยังเครื่อง Agent ได้จากที่เดียว</p></div><div className="flex flex-wrap items-center gap-2"><DistributionConnectionBadge state={connection} /><Button asChild variant="secondary"><Link href="/distribute-files">+ สร้างงานใหม่</Link></Button></div></div></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label, value, color]) => <div key={label} className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><span className={`mb-3 block size-2.5 rounded-full ${color}`} /><p className="text-xs text-muted-foreground sm:text-sm">{label}</p><p className="mt-1 text-2xl font-bold tabular-nums sm:text-3xl">{value}</p></div>)}</div>
    <section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b p-4 sm:p-5"><h2 className="font-semibold">รายการงาน</h2><p className="mt-1 text-xs text-muted-foreground">ค้นหาและตรวจสอบสถานะของแต่ละงาน</p><form className="mt-4 flex flex-col gap-3 sm:flex-row"><Input name="q" defaultValue={query} placeholder="ค้นหาชื่อไฟล์ รหัสงาน หรือห้อง..." aria-label="ค้นหางานกระจายไฟล์" className="h-10 sm:max-w-md" /><select name="status" defaultValue={filter} aria-label="กรองสถานะงาน" className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="ALL">ทุกสถานะ</option><option value="IN_PROGRESS">กำลังดำเนินการ</option><option value="COMPLETED">สำเร็จ</option><option value="PARTIAL_FAILED">สำเร็จบางส่วน</option><option value="FAILED">ไม่สำเร็จ</option></select><input type="hidden" name="limit" value={initialSnapshot.pagination.limit} /><Button type="submit">ค้นหา</Button>{(query || filter !== "ALL") && <Button asChild variant="ghost"><Link href="/file-distributions">ล้างตัวกรอง</Link></Button>}</form></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr>{["ไฟล์", "ปลายทาง", "ความคืบหน้า", "สำเร็จ", "ล้มเหลว", "ออฟไลน์", "สถานะ", "เริ่มเมื่อ", ""].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{jobs.map((job) => <JobRow key={job.id} job={job} />)}</tbody></table></div>
      <div className="divide-y md:hidden">{jobs.map((job) => <article key={job.id} className="space-y-4 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{job.filename}</p><p className="mt-1 truncate text-xs text-muted-foreground">ปลายทาง: {job.targetLabel}</p></div><DistributionStatusBadge status={job.status} /></div><DistributionProgress value={percent(job)} /><div className="flex items-center justify-between text-xs text-muted-foreground"><span>สำเร็จ {job.completedTargets} จาก {job.totalTargets} เครื่อง</span><Link href={`/file-distributions/${job.id}`} className="font-semibold text-blue-600">ดูรายละเอียด →</Link></div></article>)}</div>
      {!jobs.length && <div className="p-12 text-center"><div className="mx-auto mb-3 flex size-12 items-center justify-center rounded-full bg-muted text-xl">⌕</div><p className="font-medium">ไม่พบงานกระจายไฟล์</p><p className="mt-1 text-sm text-muted-foreground">ลองเปลี่ยนคำค้นหาหรือตัวกรอง หรือสร้างงานใหม่</p></div>}
      <footer className="flex items-center justify-between gap-3 border-t bg-muted/30 p-3 text-xs text-muted-foreground"><span>หน้า {initialSnapshot.pagination.page} จาก {Math.max(1, initialSnapshot.pagination.totalPages)} · ทั้งหมด {initialSnapshot.pagination.total} งาน</span><div className="flex gap-2"><PageButton page={initialSnapshot.pagination.page - 1} label="ก่อนหน้า" disabled={initialSnapshot.pagination.page <= 1} snapshot={initialSnapshot} query={query} filter={filter} /><PageButton page={initialSnapshot.pagination.page + 1} label="ถัดไป" disabled={initialSnapshot.pagination.page >= initialSnapshot.pagination.totalPages} snapshot={initialSnapshot} query={query} filter={filter} /></div></footer>
    </section>
  </div>;
}
function JobRow({ job }: { job: FileDistributionJob }) { return <tr className="transition-colors hover:bg-muted/35"><td className="max-w-56 px-4 py-4"><p className="truncate font-semibold" title={job.filename}>{job.filename}</p><p className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{job.id}</p></td><td className="max-w-44 truncate px-4 py-4">{job.targetLabel}</td><td className="px-4 py-4"><DistributionProgress value={percent(job)} label={`ความคืบหน้า ${job.filename}`} /></td><td className="px-4 py-4 font-medium tabular-nums text-emerald-600">{job.completedTargets} / {job.totalTargets}</td><td className="px-4 py-4 tabular-nums text-red-600">{job.failedTargets}</td><td className="px-4 py-4 tabular-nums text-muted-foreground">{job.offlineTargets}</td><td className="px-4 py-4"><DistributionStatusBadge status={job.status} /></td><td className="px-4 py-4 text-xs text-muted-foreground" title={new Date(job.createdAt).toLocaleString("th-TH")}>{formatRelativeTime(job.createdAt)}</td><td className="px-4 py-4"><Button asChild size="sm" variant="outline"><Link href={`/file-distributions/${job.id}`}>ดูรายละเอียด</Link></Button></td></tr>; }
function PageButton({ page, label, disabled, snapshot, query, filter }: { page: number; label: string; disabled: boolean; snapshot: Snapshot; query: string; filter: string }) { if (disabled) return <Button size="sm" variant="outline" disabled>{label}</Button>; return <Button asChild size="sm" variant="outline"><Link href={pageHref(page, snapshot.pagination.limit, query, filter)}>{label}</Link></Button>; }
function percent(job: FileDistributionJob) { return job.totalTargets ? job.completedTargets / job.totalTargets * 100 : 0; }
function pageHref(page: number, limit: number, query: string, filter: string) { const params = new URLSearchParams({ page: String(Math.max(1, page)), limit: String(limit) }); if (query) params.set("q", query); if (filter && filter !== "ALL") params.set("status", filter); return `/file-distributions?${params}`; }
