"use client";

import { useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import * as api from "../_lib/tokensClient";
import { getTokenStatus, localDateTime, parseTokenConstraints, type Token, type TokensSnapshot, type UpdateTokenInput } from "../_lib/types";

const tones = { red: "bg-red-50 text-red-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" };
const dateLabel = (value?: string | null) => value ? new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Bangkok" }).format(new Date(value)) : "ไม่กำหนด";
function ErrorMessage({ message }: { message: string | null }) { return message ? <p role="alert" className="my-3 text-sm text-red-600">{message}</p> : null; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2 text-sm"><span>{label}</span>{children}</label>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>; }

export default function TokenManagement({ snapshot }: { snapshot: TokensSnapshot }) {
  const [tokens, setTokens] = useState(snapshot.tokens), [error, setError] = useState(snapshot.error), [query, setQuery] = useState("");
  const [pending, setPending] = useState(false), [creating, setCreating] = useState(false), [editing, setEditing] = useState<Token | null>(null);
  const [detail, setDetail] = useState<Token | null>(null), [created, setCreated] = useState<Token | null>(null), [actionError, setActionError] = useState<string | null>(null);
  const lock = useRef(false);
  const visible = useMemo(() => { const q = query.trim().toLowerCase(); return tokens.filter(t => [t.id, t.token_type, t.creator_username, t.created_by].some(v => v?.toLowerCase().includes(q))); }, [tokens, query]);
  async function refresh() { const result = await api.listTokens(); setTokens(result.tokens); setError(null); }
  async function run(work: () => Promise<unknown>, success: string) {
    if (lock.current) return false; lock.current = true; setPending(true); setActionError(null);
    try { await work(); await refresh(); toast.success(success); return true; } catch (e) { setActionError(e instanceof Error ? e.message : "ดำเนินการไม่สำเร็จ"); try { await refresh(); } catch { /* keep action error */ } return false; } finally { lock.current = false; setPending(false); }
  }
  async function openDetail(token: Token) { setActionError(null); setDetail(token); try { const result = await api.getToken(token.id); setDetail(result); } catch (e) { setActionError(e instanceof Error ? e.message : "โหลดรายละเอียดไม่สำเร็จ"); } }
  return <>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900" aria-busy={pending}>
      <div className="flex flex-col gap-4 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">Enrollment Tokens <span className="text-sm font-normal text-slate-500">{tokens.length} รายการ</span></h2><p className="mt-1 text-sm text-slate-500">สร้าง แก้ไข และยุติการใช้งาน token โดยเก็บประวัติไว้</p></div><div className="flex gap-2"><Button variant="outline" disabled={pending} onClick={() => refresh().catch(e => setError(e.message))}>รีเฟรช</Button><Button disabled={pending || !!error} className="bg-blue-600 text-white hover:bg-blue-700" onClick={() => { setActionError(null); setCreating(true); }}>สร้าง Token</Button></div></div>
      <div className="space-y-3 p-4 sm:p-5"><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="ค้นหา ID, ประเภท หรือผู้สร้าง..." />{error && <div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}</div>
      {!visible.length ? <div className="px-6 py-14 text-center"><h3 className="font-semibold">{error ? "ไม่สามารถโหลดรายการ Tokens ได้" : "ไม่พบ Token"}</h3></div> : <div className="grid gap-4 p-4 pt-0 sm:grid-cols-2 lg:grid-cols-3">{visible.map(token => { const status = getTokenStatus(token); return <article key={token.id} className="flex flex-col rounded-2xl border p-4"><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold text-blue-600">{token.token_type ?? "enrollment"}</span><span className={`rounded-full px-2.5 py-1 text-xs ${tones[status.tone]}`}>{status.label}</span></div><p className="mt-4 break-all font-mono text-xs text-slate-500">ID: {token.id}</p><dl className="mt-4 space-y-3 text-sm"><Info label="ใช้แล้ว" value={`${token.used_count.toLocaleString()} / ${token.max_use == null ? "ไม่จำกัด" : token.max_use.toLocaleString()} ครั้ง`} /><Info label="หมดอายุ" value={dateLabel(token.expires_at)} /><Info label="สร้างเมื่อ" value={dateLabel(token.created_at)} /></dl><div className="mt-auto flex flex-wrap gap-2 pt-5"><Button size="sm" variant="outline" disabled={pending} onClick={() => openDetail(token)}>รายละเอียด</Button><Button size="sm" variant="outline" disabled={pending || token.is_revoked} onClick={() => { setActionError(null); setEditing(token); }}>แก้ไข</Button><Button size="sm" variant="destructive" disabled={pending || token.is_revoked} onClick={() => { if (window.confirm("ยืนยันยุติการใช้งาน Token นี้? การดำเนินการจะเก็บประวัติไว้และไม่สามารถกู้คืนได้")) void run(() => api.deleteToken(token.id), "ยุติการใช้งาน Token แล้ว"); }}>ยุติการใช้งาน</Button></div></article>; })}</div>}
      <div className="border-t p-4 text-xs text-slate-500">แสดง {visible.length} จาก {tokens.length} รายการ · DELETE จะ revoke token และไม่ลบประวัติ</div>
    </section>
    {(creating || editing) && <TokenForm token={editing ?? undefined} pending={pending} error={actionError} onClose={() => { setCreating(false); setEditing(null); }} onSubmit={async values => { const ok = await run(() => editing ? api.updateToken(editing.id, values) : api.createToken(values).then(setCreated), editing ? "อัปเดตเงื่อนไขแล้ว" : "สร้าง Token เรียบร้อยแล้ว"); if (ok) { setCreating(false); setEditing(null); } }} />}
    <Dialog open={created !== null} onOpenChange={open => !open && setCreated(null)}><DialogContent><DialogHeader><DialogTitle>สร้าง Token สำเร็จ</DialogTitle><DialogDescription>ค่านี้จะแสดงเฉพาะตอนสร้าง กรุณาคัดลอกและเก็บไว้อย่างปลอดภัย</DialogDescription></DialogHeader><code className="select-all break-all rounded-xl bg-slate-50 p-4 text-sm">{created?.token}</code><DialogFooter><Button onClick={() => { if (created?.token) navigator.clipboard.writeText(created.token).then(() => toast.success("คัดลอก Token แล้ว")); }}>คัดลอก</Button><Button variant="outline" onClick={() => setCreated(null)}>ปิด</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={detail !== null} onOpenChange={open => !open && setDetail(null)}><DialogContent><DialogHeader><DialogTitle>รายละเอียด Token</DialogTitle><DialogDescription>ข้อมูลจาก GET /api/tokens/:id</DialogDescription></DialogHeader>{detail && <dl className="space-y-3 text-sm"><Info label="ID" value={detail.id} /><Info label="ผู้สร้าง" value={detail.creator_username ?? detail.created_by ?? "ไม่ระบุ"} /><Info label="ใช้แล้ว" value={`${detail.used_count} / ${detail.max_use == null ? "ไม่จำกัด" : detail.max_use}`} /><Info label="หมดอายุ" value={dateLabel(detail.expires_at)} /><Info label="สถานะ" value={getTokenStatus(detail).label} /></dl>}<ErrorMessage message={actionError} /></DialogContent></Dialog>
  </>;
}

function TokenForm({ token, pending, error, onClose, onSubmit }: { token?: Token; pending: boolean; error: string | null; onClose: () => void; onSubmit: (input: UpdateTokenInput) => Promise<void> }) {
  const [maxUse, setMaxUse] = useState(token?.max_use?.toString() ?? ""), [expiresAt, setExpiresAt] = useState(localDateTime(token?.expires_at ?? undefined)), [validationError, setValidationError] = useState<string | null>(null);
  async function submit(e: FormEvent) { e.preventDefault(); setValidationError(null); try { await onSubmit(parseTokenConstraints(maxUse, expiresAt)); } catch (e) { setValidationError(e instanceof Error ? e.message : "ข้อมูลไม่ถูกต้อง"); } }
  return <Dialog open onOpenChange={open => !open && !pending && onClose()}><DialogContent><DialogHeader><DialogTitle>{token ? "แก้ไขเงื่อนไข Token" : "สร้าง Token ใหม่"}</DialogTitle><DialogDescription>กำหนด max_use และ expires_at ได้ตามต้องการ เว้นว่างเพื่อไม่จำกัด</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><fieldset disabled={pending} className="space-y-4"><Field label="จำนวนครั้งสูงสุด"><Input type="number" min="1" step="1" value={maxUse} onChange={e => setMaxUse(e.target.value)} placeholder="ไม่จำกัด" /></Field><Field label="วันหมดอายุ"><Input type="datetime-local" step="1" value={expiresAt} onChange={e => setExpiresAt(e.target.value)} /></Field></fieldset><ErrorMessage message={validationError || error} /><DialogFooter><Button type="button" variant="outline" onClick={onClose}>ยกเลิก</Button><Button type="submit" disabled={pending}>{pending ? "กำลังบันทึก..." : token ? "บันทึก" : "สร้าง Token"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
